<?php

define('SMTP_SERVER', 'VALUE_SMTP_SERVER');
define('SMTP_PORT', VALUE_SMTP_PORT);
define('SMTP_REALNAME', 'VALUE_SMTP_REALNAME');
define('SMTP_USER', 'VALUE_SMTP_USER');
define('SMTP_PASS', 'VALUE_SMTP_PASS');

define('RECIPIENT', 'VALUE_RECIPIENT');
define('RECIPIENT_REALNAME', 'VALUE_REALNAME_RECIPIENT');

?>
